#!/bin/python3

try:
    import libfmake
except ModuleNotFoundError:
    print("[ERROR] You need to install libfmake, or add libfmake to your PYTHONPATH")
    exit()

version = "1.4.2"

import sys
import os

sys.argv.pop(0)

helps = ["help","--help","-?","-h"]
versions = ["-v","--version","version"]

def setVar(vals=("gcc","main.c","main",True,"Compiling done!",False,False,"-j$(nproc)")):
    global var
    var = vals
 
setVar()


def getVer():
    print(version)
    exit()

def getHelp():
    print("Usage: fmake [OPTION...] [RULE...]")
    print()
    print("Options:")
    print("rule\tcompiles a specific rule")
    print("example\tgenerates an example make.fmake config")
    print("debug\tprints the value of all possible variables")
    print("project\tmakes a build/ & src/ directory along with a custom make.fmake files")
    print("clean\tremoves any detected compiled executables")
    print("version\tprints fmake version")
    print()
    print("Rules:")
    print("To compile a specific rule a <rule>.fmake file must be present")
    print("along with that, you can compile the rule by running fmake rule <rule>")
    print("If you just want to compile the default make.fmake, just run fmake")

def debug():
    print(f"CC:\t{var[0]}")
    print(f"SRC\t{var[1]}")
    print(f"OUT\t{var[2]}")
    print(f"MSG\t{var[3]}")
    print(f"SAY\t{var[4]}")
    print(f"RUN\t{var[5]}")
    print(f"MKE\t{var[6]}")
    print(f"MKF\t{var[7]}")
    exit()

def comp():

    if not var[6]:
        os.system(f"{var[0]} {var[1]} -o {var[2]}")
    if var[6]:
        os.system(f"make {var[7]}")
    if var[3]:
        print(var[4])
    if var[5] and not var[7]:
        os.system(f"./{var[2]}")
    exit()

def clean():
    if os.path.exists(var[2]):
        print(f"CLEAN\t{var[2]}")
        os.remove(var[2])
    exit()


def example():
    if os.path.exists("make.fmake"):
        a = input("Overwrite existing make.fmake file? (y/N) ")
        if a.lower() == "y":
            libfmake.genConfig("make.fmake",True)
        else:
            exit()
    else:
        libfmake.genConfig("make.fmake",True)

def project():
    os.mkdir("build")
    os.mkdir("src")
    libfmake.genConfig("make.fmake",True,"gcc","src/main.c","build/main")

if len(sys.argv) == 1 and sys.argv[0] in helps:
    getHelp()
elif len(sys.argv) == 1:
    if sys.argv[0] == "debug":
        setVar(libfmake.readConfig("make.fmake"))
        debug()
    elif sys.argv[0] in versions:
        getVer()
    elif sys.argv[0] == "clean":
        setVar(libfmake.readConfig("make.fmake"))
        clean()
    elif sys.argv[0] == "example":
        example()
    elif sys.argv[0] == "project":
        project()
    elif sys.argv[0] == "make-lib":
        setVar(libfmake.readConfig("make.fmake"))
        comp()

elif len(sys.argv) == 2:
    if sys.argv[0] == "debug":
        setVar(libfmake.readConfig(sys.argv[1]))
        debug()
    elif sys.argv[0] == "clean":
        setVar(libfmake.readConfig(sys.argv[1]))
        clean()
    elif sys.argv[0] == "rule":
        setVar(libfmake.readConfig(sys.argv[1]))
        comp()
elif len(sys.argv) == 0:
    setVar(libfmake.readConfig("make.fmake"))
    comp()
