#!/usr/bin/env python3
version = "1.6.4"
import os
import libfmake
import sys
sys.argv.pop(0)

vals = {
        "cc":"gcc",
        "src":"main.c",
        "out":"main",
        "msg":True,
        "say":"Compiling done!",
        "run":False,
        "mke":False,
        "mkf":"-j$(nproc)"
        }

def lis():
    a = os.listdir()
    for i in a:
        if len(i) > 7 and i[-6:] == ".fmake":
            print(i[:-6])

def comp():
    
    if not vals["mke"]:
        os.system(f"{vals['cc']} -o {vals['out']} {vals['src']}")
    else:
        os.system(f"make {vals['mkf']}")
    if vals["msg"]:
        print(vals['say'])
    if vals["run"]:
        os.system(f"./{vals['out']}")

def debug():
    for i in vals:
        print(f"{i.upper()}:\t{vals[i]}")

def clean():
    if os.path.exists(vals["out"]):
        os.remove(vals["out"])

if len(sys.argv) == 0:
    if not os.path.exists("make.fmake"):
        print("fmake: No make.fmake file")
        exit(1)
    with open("make.fmake","r") as f:
        vals = libfmake.loads(f.read())
        f.close()
    comp()

elif len(sys.argv) == 1:
    match sys.argv[0]:
        case "debug":
            if os.path.exists("make.fmake"):
                with open("make.fmake","r") as f:
                    vals = libfmake.loads(f.read())
                    f.close()
            else:
                print("fmake: No make.fmake file")
                exit(1)
            debug()
        case "clean":
            if os.path.exists("make.fmake"):
                with open("make.fmake","r") as f:
                    vals = libfmake.loads(f.read())
                    f.close()
            else:
                print("fmake: No make.fmake file")
                exit(1)
            clean()
        case "version" | "--version" | "-v":
            print(version)
        case "list":
            lis()
        case "project":
            if not os.path.exists("src/"):
                os.mkdir("src")
            if not os.path.exists("build/"):
                os.mkdir("build")
            if not os.path.exists("src/main.c"):
                f = open("src/main.c","w")
                f.write("#include <stdio.h>\n\nint main(void) {\n\treturn 0;\n}\n")
                f.close()
            if not os.path.exists("make.fmake"):
                f = open("make.fmake","w")
                f.write(libfmake.dumps({"cc":"gcc","src":"src/main.c","out":"build/main","mke":False,"run":False}))
                f.close()
        case "example":
            f = open("make.fmake","w")
            f.write(libfmake.dumps(vals))
            f.close()
        case "help" | "--help" | "-h" | "-?":
            print("Usage: fmake [keyword] [rule]")
            print()
            print("Keywords:")
            print("rule    - Compiles a specific rule. To make a rule just make a <rule>.fmake file.")
            print("clean   - Removes the compiled executable.")
            print("debug   - Prints all the values of specific rule.")
            print("example - Generates an example make.fmake file.")
            print("project - Makes a build/ & src/ directory along with a custom make.fmake file.")
            print("list    - Lists all available rules.")
            print("version - Returns the current version of fmake.")
            print()
            print("Note: Example, list, project, and version require no rule.")
            print("Note: If no rule is passed to rule, clean, or debug it will default to make.fmake, if it exists.")

elif len(sys.argv) > 1:
    if sys.argv[0] == "rule":
        if os.path.exists(sys.argv[1] + ".fmake"):
            with open(sys.argv[1] + ".fmake","r") as f:
                vals = libfmake.loads(f.read())
                f.close()
            comp()
        else:
            print(f"fmake: '{sys.argv[1]}.fmake' does not exist")
            exit(1)
    elif sys.argv[0] == "debug":
        if os.path.exists(sys.argv[1] + ".fmake"):
            with open(sys.argv[1] + ".fmake","r") as f:
                vals = libfmake.loads(f.read())
                f.close()
            debug()
        else:
            print(f"fmake: '{sys.argv[1]}.fmake' does not exist")
            exit(1)
    elif sys.argv[0] == "clean":
        if os.path.exists(sys.argv[1] + ".fmake"):
            with open(sys.argv[1] + ".fmake","r") as f:
                vals = libfmake.loads(f.read())
                f.close()
            clean()
        else:
            print(f"fmake: '{sys.argv[1]}.fmake' does not exist")
            exit(1)
